name: Semgrep

on:
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - '**.py'

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v2
      - name: Semgrep Scan
        run: semgrep ci --exclude=examples --exclude=tests --exclude=docs .
        env:
          SEMGREP_APP_TOKEN: 72615276da0e85def433ac4d43c9a299ba71021740703d5ebf1e0756f31636bf
          
